import React, { Suspense } from "react";
import "./globals.css";
// import { ErrorBoundary } from "next/dist/client/components/error-boundary";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'My dashboard',
  description: 'This is dashboard handles all internal process background.',
  openGraph: {
    title: "Next Route",
    description: "This dasboard is Generated by create next app",
    url: "https://miro.medium.com/1*FA4XLQhKWhDFPu752UAIcg.jpeg",
    siteName: "Next Route",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {" "}
        <Suspense fallback={<div className="text-cyan-400">Loading...</div>}>
          {children}
        </Suspense>
        {/* <ErrorBoundary fallback={<Error />}></ErrorBoundary> */}
      </body>
    </html>
  );
}